### ISSUE TITLE
Update UI and Functionality - Hotfix

### ISSUE THREAD

**Issue by Dammyjay93** [Font-Duo/Font-Duo-UI#7]
1. Fix jumping behaviour of font name text: text should hug content and not split into 2 lines
2. Create an empty state ui for when a "vibe" has not been selected
3. Make entire preview area have a fixed height to prevent jumping behaviour
4. Remove "more" btn and add 3 more btn selectors
5. Determine algorithm logic

**Comment by Oyinbayode** [comment]
1. Font Name Text issue fixed ✅
2. Previwe area height fixed ✅

**Comment by Oyinbayode** [comment]
All done and implemented ✅
